### ISSUE TITLE
Will not run

### ISSUE THREAD

**Issue by delaneyj** [43081j/tailwind-lit-example#2]
bundle.js:570 Uncaught SyntaxError: The requested module '/hello-world-4K4DCJGM.css' does not provide an export named 'default' (at bundle.js:570:8)

**Comment by 43081j** [comment]
just tried this myself. are you using vite?

it seems vite strips the import assertions for whatever reason, so chrome tries to load the css as if it were JS 🤔 

if i run a basic web server to serve it, everything works fine. the vite transforms mess it up 😞

**Comment by delaneyj** [comment]
Yeah its a vite issue, however vite-plugin-lit-css did solve my issues I'll close this for now as you were explicitly trying to support a vite / hot reload setup.
